steps:
  - id: test-and-lint
    name: node:20-bookworm-slim
    entrypoint: bash
    args:
      - -ceu
      - |
        npm ci
        npm test
        npm run lint

  - id: container-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - forusbots-verify:$BUILD_ID
      - .

serviceAccount: projects/forusbots/serviceAccounts/forusbots-cloudbuild@forusbots.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
